
version: '2.1'
services:
 mongodb:
    extends:
      file: docker-compose-base.yml
      service: base-mongodb
    container_name: ${CONTAINER_HOST_NAME:-mongodb}
    hostname: ${CONTAINER_HOST_NAME:-mongodb}
    network_mode: bridge
    ports:
    - "${MONGO_27017_PORT:-27017}:27017"
    volumes:
    - data:/data/db
    - config:/data/configdb

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/configdb
      o: bind

