version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-mongodb
    container_name: ${CONTAINER_HOST_NAME:-standalone.mongodb}
    hostname: ${CONTAINER_HOST_NAME:-standalone.mongodb}
    networks:
      local-network:
        ipv4_address: 172.16.238.58
        #ipv6_address: 2001:3984:3989::58
    ports:
    - "${MONGO_27017_PORT:-27017}:27017"
    restart: always
    volumes:
    - config:/data/configdb
    - data:/data/db

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/configdb
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind
